apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudphotomanager
  labels:
    app: cloudphotomanager
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cloudphotomanager
  template:
    metadata:
      labels:
        app: cloudphotomanager
    spec:
      containers:
        - image: cloudphotomanager
          name: cloudphotomanager
          resources:
            limits:
              memory: 500Mi
              cpu: 1
            requests:
              memory: 20Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /data
              name: pod-volume
          imagePullPolicy: Always
      volumes:
        - name: pod-volume
          persistentVolumeClaim:
            claimName: cloudphotomanager
