apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudphotomanager
resources:
  - base/namespace.yaml
  - base/pvc.yaml
  - base/deployment.yaml
  - base/service.yaml
images:
  - name: cloudphotomanager
    newTag: latest
    newName: didierhoarau/cloudphotomanager
